#!/bin/bash
# run-agent-docker.sh — build + run the student agent as a Docker container.
# This is the default run path invoked by setup.sh; the capi-agent systemd
# service is the opt-in alternative (AGENT_RUNTIME=systemd).
#
# Usage:
#   ./run-agent-docker.sh up      # generate .env, build image, start (default)
#   ./run-agent-docker.sh down    # stop and remove the container
#   ./run-agent-docker.sh logs    # follow container logs
#   ./run-agent-docker.sh status  # show container status
#
# Configuration (env vars, same contract as setup.sh):
#   DASHBOARD_URL         Full report URL. If unset, built from INSTRUCTOR_IP.
#   INSTRUCTOR_IP         Instructor host IP (→ http://IP:8000/api/report).
#   DASHBOARD_API_TOKEN   Per-student token (REQUIRED).
#   STUDENT_ID            Deterministic student id (optional; FQDN fallback).
#   KUBE_DIR              Student's kube dir (default: student ~/.kube).
#   LEADERBOARD_OPT_IN    true/false (default false).
#   DASHBOARD_INSECURE_HTTP  true to silence the plaintext-http warning.
set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# agent -> student -> module-00-setup -> repo root
REPO_ROOT="$( cd "$SCRIPT_DIR/../../.." && pwd )"
ENV_FILE="$SCRIPT_DIR/.env"

# --- docker compose detection (plugin v2 preferred, legacy fallback) ----------
if docker compose version >/dev/null 2>&1; then
  DC=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  DC=(docker-compose)
else
  echo "ERROR: neither 'docker compose' nor 'docker-compose' is available." >&2
  exit 1
fi
compose() { (cd "$SCRIPT_DIR" && "${DC[@]}" "$@"); }

ACTION="${1:-up}"

# down/logs/status only identify already-created resources, but compose still
# interpolates the whole file (which marks several vars required for `up`). When
# no .env has been generated yet, feed harmless placeholders so those read-only
# subcommands don't abort on missing-variable errors. Never do this for `up` —
# there the real values must reach compose.
if [ ! -f "$ENV_FILE" ] && { [ "$ACTION" = down ] || [ "$ACTION" = logs ] || [ "$ACTION" = status ]; }; then
  export WORKSHOP_ROOT_HOST="/nonexistent" KUBE_DIR="/nonexistent" \
         DASHBOARD_URL="http://unused" DASHBOARD_API_TOKEN="unused"
fi

case "$ACTION" in
  down)   compose down; exit 0 ;;
  logs)   compose logs -f; exit 0 ;;
  status) compose ps; exit 0 ;;
  up)     : ;;  # fall through to the build/run path below
  *) echo "Unknown action: $ACTION (use up|down|logs|status)" >&2; exit 1 ;;
esac

# --- resolve the student identity (UID/GID + kube dir) ------------------------
# When invoked via sudo, target the *student* account, not root, so files the
# container writes into the repo stay student-owned and it reads the student's
# kubeconfig.
STUDENT_USER="${SUDO_USER:-$USER}"
if [ "$STUDENT_USER" = "root" ]; then
  echo "WARNING: running as root with no SUDO_USER — files will be root-owned." >&2
  AGENT_UID="$(id -u)"; AGENT_GID="$(id -g)"; STUDENT_HOME="$HOME"
else
  AGENT_UID="$(id -u "$STUDENT_USER")"
  AGENT_GID="$(id -g "$STUDENT_USER")"
  STUDENT_HOME="$(getent passwd "$STUDENT_USER" | cut -d: -f6)"
fi
KUBE_DIR="${KUBE_DIR:-$STUDENT_HOME/.kube}"

# --- resolve dashboard URL + token -------------------------------------------
if [ -z "${DASHBOARD_URL:-}" ]; then
  if [ -n "${INSTRUCTOR_IP:-}" ]; then
    DASHBOARD_URL="http://${INSTRUCTOR_IP}:8000/api/report"
  else
    echo "ERROR: set DASHBOARD_URL or INSTRUCTOR_IP." >&2
    exit 1
  fi
fi
if [ -z "${DASHBOARD_API_TOKEN:-}" ]; then
  echo "ERROR: DASHBOARD_API_TOKEN is required." >&2
  exit 1
fi

if [ ! -f "$KUBE_DIR/config" ]; then
  echo "WARNING: $KUBE_DIR/config not found — the agent cannot reach clusters" >&2
  echo "         until the student has created the kind management cluster." >&2
fi

# --- write .env for docker-compose -------------------------------------------
umask 077  # the token lives here — keep .env private
cat > "$ENV_FILE" <<EOF
# Generated by run-agent-docker.sh — contains a secret token, do not commit.
AGENT_UID=$AGENT_UID
AGENT_GID=$AGENT_GID
WORKSHOP_ROOT_HOST=$REPO_ROOT
KUBE_DIR=$KUBE_DIR
DASHBOARD_URL=$DASHBOARD_URL
DASHBOARD_API_TOKEN=$DASHBOARD_API_TOKEN
STUDENT_ID=${STUDENT_ID:-}
LEADERBOARD_OPT_IN=${LEADERBOARD_OPT_IN:-false}
DASHBOARD_INSECURE_HTTP=${DASHBOARD_INSECURE_HTTP:-false}
EOF

echo ">>> Building and starting capi-agent container..."
echo "    repo:        $REPO_ROOT"
echo "    kube dir:    $KUBE_DIR"
echo "    dashboard:   $DASHBOARD_URL"
echo "    run as:      $STUDENT_USER ($AGENT_UID:$AGENT_GID)"
compose up -d --build

echo ""
echo "✅ capi-agent container is up."
echo "   Logs:   $SCRIPT_DIR/run-agent-docker.sh logs"
echo "   Stop:   $SCRIPT_DIR/run-agent-docker.sh down"
